### ISSUE TITLE
Abandoned project?

### ISSUE THREAD

**Issue by jonatanblue** [astraw/stdeb#125]
This project has 30 open issues, some of them dating back to 2012, most of them with no comment or no clear direction.

The last accepted PR was in June this year.

Is this project abandoned/not maintained?

**Comment by timofurrer** [comment]
June doesn't seem to be that long ago - I wouldn't call it abandoned ..

@contributors: Are you guys looking for maintainers? I'd love to see this project kept going!

:beers:

**Comment by astraw** [comment]
Hi all, I would be very happy to see another person or persons take over this project. As is obvious, my energies are elsewhere and stdeb Works For Me. stdeb is challenging because integration testing requires all kinds of configurations that many PRs don't necessarily take into account. I would say the first thing to do is to improve automation of the test suite we've got (e.g. `test2and3.sh`). Probably the best maintainers would be folks already with a lot of packaging experience (e.g. @dirk-thomas perhaps?).

I don't want to impede progress but in this case I'm not sure I can help, either.

**Comment by p1otr** [comment]
shameless plug: I created PyPI2deb (https://github.com/p1otr/pypi2deb) which at the beginning was meant to use stdeb, but in the end I wrote everything from scratch (i.e. added py2dsp which does what stdeb does for single package). It doesn't have all the stdeb's functionality, but it helps me a lot already to do initial packaging work for Debian.

**Comment by dirk-thomas** [comment]
I have to respond with the same as @astraw: my energies are elsewhere and stdeb works for me. Sorry.

**Comment by jonatanblue** [comment]
Thanks for clarifying your positions on this.

It would be great if you could put a note about this at the top of the README, so new-comers are aware that the project is not actively maintained

**Comment by bersace** [comment]
@astraw there is no worry with not being able to maintain a project. Thanks for all the work done yet. It's nice to have so many contribution to stdeb !

What do you need to open maintenance of stdeb ?

**Comment by astraw** [comment]
As mentioned, the main thing I think needed is an integration test suite. This seems necessary to avoid unintentionally causing incompatibilities or other problems, and thus has been the first priority for me with stdeb.

Ideally this tests the generated source packages across the range of supported distributions. (This would also require being explicit about what is a "supported distribution".) It seems a reasonable goal would be Debian stable, testing and unstable as well as current Ubuntu and Ubuntu LTS. (The specific distributions this means would be updated over time.)

**Comment by bersace** [comment]
@astraw i agree, we need tests. Do you mean a Jenkins ?

**Comment by bersace** [comment]
I found https://github.com/jordansissel/fpm/ very useful.

**Comment by astraw** [comment]
@bersace, I have seen fpm before but never looked beyond the README. With specific relation to this issue, how do you think fpm could help?

**Comment by bersace** [comment]
@astraw If you just need to translate a pypi package to .deb (and or .rpm, pacman, etc.) fpm is neat. If you need a managed repository (APT, RPM, etc.) https://packager.io/ should do the trick.

stdeb is nice to bootstrap a debian source package if you need to care the burden of managing debian source package (e.g. with gbp).

That's my point of view for now.

**Comment by astraw** [comment]
I see, so it doesn't get us closer to a good CI setup, just provides an alternative for people. Fair enough.

**Comment by bersace** [comment]
I think that CircleCI 2.0 should help for a better CI. It allows to trigger several images.

I started a PoC here https://github.com/bersace/stdeb/pull/1. I had pain with stdeb testing strategy.

**Comment by mikepurvis** [comment]
Travis also lets you test multiple environments, especially since you can do stuff like suck down different docker containers to run your stuff in, eg:

https://docs.travis-ci.com/user/docker/

I think the hard part is less the mechanics of it, it's establishing what the required test cases even _are_, and automatically detecting even subtle failures, such as issues with properly propagating versioned dependencies, or Py2/3 dual builds.

**Comment by jimporter** [comment]
One question I have here is: assuming stdeb got a bunch of good integration tests so that it's easy to verify that PRs aren't regressing things, would someone be willing to shepherd those PRs into master and occasionally publish new releases? I'm happy to help get tests in better shape and work on other bits here and there, but I don't think I'd be able to commit to being the primary maintainer for this.

If there are folks out there who are willing to handle the project management side once stdeb is full of good tests, I'll start looking into how to get those tests written. (It'd be silly to spend a bunch of time on tests and then not have someone to manage the project afterwards...)

**Comment by astraw** [comment]
Perhaps the best approach is for me to transfer ownership to the [Debian Python Modules Team (DPMT)](https://wiki.debian.org/Teams/PythonModulesTeam) . I see they maintain [a git repo](https://salsa.debian.org/python-team/modules/stdeb) with their patches and it looks like @onovy is the most recent committer there. @onovy, or others, do you have a suggestion for how I can best turn over control to the DPMT?

**Comment by onovy** [comment]
probably just abadon project on github: write information into README about new home of project and remove all files from git, keep only README. That will keep history. Same approach we are using in OpenStack projects.

**Comment by p1otr** [comment]
> Perhaps the best approach is for me to transfer ownership to the
> [Debian Python Modules Team
> (DPMT)](https://wiki.debian.org/Teams/PythonModulesTeam) . I see they

DPMT's purpose is to package Python modules… not really to act as a
place for upstream projects. That said, it's a home for pypi2deb (which
also can be used as stdeb replacement, BTW) so I guess stdeb can be
moved as well, but only if there will be at last one human volunteer
that maintains it.

**Comment by jimporter** [comment]
Perhaps the Python Packaging Authority would have some interest in maintaining things? I'll try and see if they'd be willing...

**Comment by astraw** [comment]
@jimporter thanks.

**Comment by dirk-thomas** [comment]
> I have to respond with the same as @astraw: my energies are elsewhere and stdeb works for me. Sorry.

With the upcoming Python 2 EOL we have a need to specify different suites or Python 2 and Python 3 packages generated by `stdeb`. A coworker of mine has created a PR for that (see #147). So one way or the other we need `stdeb` with this change. We can either use a fork from that branch (rather inconvenient) or get it upstreamed.

While many people commented here nobody seems to be willing to pick up the maintainer role. Instead of using a fork I am willing to do limited amount of work. That would including reviewing and (reasonable) testing of (not too complex) PRs but it would certainly exclude any kind of development for issues without a PR.

@astraw Would you be up for adding me to this repo as well as the PyPI package or do you want me to run changes by you for now and let you hit the merge buttons and do releases (assuming you have time to do so)? It seems the first action item would be to get CI to turn over before going through pending PRs...

**Comment by astraw** [comment]
@dirk-thomas I added you as a maintainer on PyPI and requested that github send you an invite for push access to this repo.

I fully understand not being able to invest much time. I am grateful that you may be able to do a limited about of reviewing and merging. Thank you so much!

**Comment by dirk-thomas** [comment]
Thanks @astraw for granting me access.

Before I joined ~10 commits have landed on `master` since the latest release 0.8.5 on Feb 18th 2015.

I first fixed the Travis CI builds to pass. Since then I closed 4 issues, merged 5 PRs (which resolved another issue) and commented on most pending PRs (either asking for something or clarifying why it hasn't been accepted yet).

I am at a point where I think it makes sense to cut a new release. Since technically the upcoming version is changing behavior (e.g. by removing `dh_desktop`) I am leaning towards calling it 0.9.0. Any opinions on that proposal?

Since many people have commented on this ticket I assume you all have a vested interest that this package continuous to be maintained and even more important doesn't break any of your workflows. Therefore I would like to ask all of you to try the current state of `master` for your use case and leave a brief comment if you see a problem (please also comment if it works fine for you). That would increase the confidence before cutting a new release. Thanks.

**Comment by astraw** [comment]
Thanks @dirk-thomas for this work, it is much appreciated! I think a 0.9.0 release soon is a good idea. If there are new bugs, we can hopefully release a 0.9.1 if fixing requires no further change in behavior or a 0.10.0 if it does. Both options seem reasonable to me.

**Comment by dirk-thomas** [comment]
With the upcoming release of version 0.9.0 (#149) I am going to close this.
